import type { AccountType, AccountWithType, BalanceSheetSummary, AccountTransaction } from "@/app/balancesheet/types";

// Sample account types (mimicking system defaults)
export const sampleAccountTypes: AccountType[] = [
	{
		id: "type-1",
		user_id: null,
		name: "Savings Account",
		class: "asset",
		category: "banking",
		is_tax_advantaged: false,
		icon: "piggy-bank",
		sort_order: 2,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
	{
		id: "type-2",
		user_id: null,
		name: "Emergency Fund",
		class: "asset",
		category: "banking",
		is_tax_advantaged: false,
		icon: "shield",
		sort_order: 4,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
	{
		id: "type-3",
		user_id: null,
		name: "Investment Account",
		class: "asset",
		category: "investment",
		is_tax_advantaged: false,
		icon: "trending-up",
		sort_order: 10,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
	{
		id: "type-4",
		user_id: null,
		name: "Checking Account",
		class: "asset",
		category: "banking",
		is_tax_advantaged: false,
		icon: "wallet",
		sort_order: 1,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
	{
		id: "type-5",
		user_id: null,
		name: "Tax-Advantaged Savings",
		class: "asset",
		category: "retirement",
		is_tax_advantaged: true,
		icon: "shield-check",
		sort_order: 20,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
	{
		id: "type-6",
		user_id: null,
		name: "Credit Card",
		class: "liability",
		category: "credit",
		is_tax_advantaged: false,
		icon: "credit-card",
		sort_order: 40,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
	{
		id: "type-7",
		user_id: null,
		name: "Student Loan",
		class: "liability",
		category: "debt",
		is_tax_advantaged: false,
		icon: "graduation-cap",
		sort_order: 52,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
	{
		id: "type-8",
		user_id: null,
		name: "Auto Loan",
		class: "liability",
		category: "debt",
		is_tax_advantaged: false,
		icon: "car",
		sort_order: 53,
		is_system: true,
		is_active: true,
		created_at: "2024-01-01",
	},
];

export const sampleAccounts: AccountWithType[] = [
	// Assets
	{
		id: "acc-1",
		user_id: "sample-user",
		name: "Emergency Fund",
		account_type_id: "type-2",
		account_type: sampleAccountTypes[1],
		institution: "Ally Bank",
		account_number_last4: null,
		current_balance: 8500,
		currency: "CAD",
		credit_limit: null,
		original_amount: null,
		interest_rate: 0.045,
		interest_type: "compound",
		loan_start_date: null,
		loan_term_months: null,
		target_balance: 10000,
		track_contribution_room: false,
		contribution_room: null,
		annual_contribution_limit: null,
		notes: "High-yield savings for emergencies",
		color: null,
		icon: null,
		display_order: 1,
		is_active: true,
		external_account_id: null,
		created_at: "2024-01-15T10:00:00Z",
		updated_at: "2024-12-15T10:00:00Z",
	},
	{
		id: "acc-2",
		user_id: "sample-user",
		name: "Robinhood",
		account_type_id: "type-3",
		account_type: sampleAccountTypes[2],
		institution: "Robinhood",
		account_number_last4: null,
		current_balance: 32100,
		currency: "CAD",
		credit_limit: null,
		original_amount: null,
		interest_rate: null,
		interest_type: null,
		loan_start_date: null,
		loan_term_months: null,
		target_balance: 50000,
		track_contribution_room: false,
		contribution_room: null,
		annual_contribution_limit: null,
		notes: "Index funds and stocks",
		color: null,
		icon: null,
		display_order: 2,
		is_active: true,
		external_account_id: null,
		created_at: "2023-06-01T10:00:00Z",
		updated_at: "2024-12-15T10:00:00Z",
	},
	{
		id: "acc-3",
		user_id: "sample-user",
		name: "TFSA",
		account_type_id: "type-5",
		account_type: sampleAccountTypes[4],
		institution: "Wealthsimple",
		account_number_last4: null,
		current_balance: 45000,
		currency: "CAD",
		credit_limit: null,
		original_amount: null,
		interest_rate: null,
		interest_type: null,
		loan_start_date: null,
		loan_term_months: null,
		target_balance: 95000,
		// Contribution room tracking enabled
		track_contribution_room: true,
		contribution_room: 7000,
		annual_contribution_limit: 7000,
		notes: "Tax-free savings for retirement",
		color: null,
		icon: null,
		display_order: 3,
		is_active: true,
		external_account_id: null,
		created_at: "2022-03-10T10:00:00Z",
		updated_at: "2024-12-15T10:00:00Z",
	},

	// Liabilities
	{
		id: "acc-4",
		user_id: "sample-user",
		name: "Chase Sapphire Reserve",
		account_type_id: "type-6",
		account_type: sampleAccountTypes[5],
		institution: "Chase",
		account_number_last4: "4521",
		current_balance: 2450,
		currency: "CAD",
		credit_limit: 15000,
		original_amount: null,
		interest_rate: 0.2499,
		interest_type: "compound",
		loan_start_date: null,
		loan_term_months: null,
		target_balance: null,
		track_contribution_room: false,
		contribution_room: null,
		annual_contribution_limit: null,
		notes: "Pay in full each month",
		color: null,
		icon: null,
		display_order: 1,
		is_active: true,
		external_account_id: null,
		created_at: "2023-01-05T10:00:00Z",
		updated_at: "2024-12-15T10:00:00Z",
	},
	{
		id: "acc-5",
		user_id: "sample-user",
		name: "Student Loans",
		account_type_id: "type-7",
		account_type: sampleAccountTypes[6],
		institution: "Navient",
		account_number_last4: null,
		current_balance: 18500,
		currency: "CAD",
		credit_limit: null,
		original_amount: 25000,
		interest_rate: 0.055,
		interest_type: "compound",
		loan_start_date: "2020-09-01",
		loan_term_months: 120,
		target_balance: null,
		track_contribution_room: false,
		contribution_room: null,
		annual_contribution_limit: null,
		notes: "Minimum payment $285/mo",
		color: null,
		icon: null,
		display_order: 2,
		is_active: true,
		external_account_id: null,
		created_at: "2020-09-01T10:00:00Z",
		updated_at: "2024-12-15T10:00:00Z",
	},
];

export const sampleBalanceSheetSummary: BalanceSheetSummary = {
	totalAssets: 85600,
	totalLiabilities: 20950,
	netWorth: 64650,
	previousTotalAssets: 82500,
	previousTotalLiabilities: 21200,
	previousNetWorth: 61300,
	assetAccounts: sampleAccounts.filter((acc) => acc.account_type?.class === "asset"),
	liabilityAccounts: sampleAccounts.filter((acc) => acc.account_type?.class === "liability"),
};

export const sampleAccountTransactions: Record<string, AccountTransaction[]> = {
	"acc-1": [
		{
			id: "txn-1",
			account_id: "acc-1",
			user_id: "sample-user",
			amount: 500,
			transaction_type: "deposit",
			description: "Monthly savings",
			transaction_date: "2024-12-15",
			linked_allocation_transaction_id: "tx-linked-savings",
			created_at: "2024-12-15T10:00:00Z",
		},
		{
			id: "txn-2",
			account_id: "acc-1",
			user_id: "sample-user",
			amount: 14.22,
			transaction_type: "interest",
			description: "Monthly compound interest",
			transaction_date: "2024-12-01",
			linked_allocation_transaction_id: null,
			created_at: "2024-12-01T00:00:00Z",
		},
	],
	"acc-3": [
		{
			id: "txn-3",
			account_id: "acc-3",
			user_id: "sample-user",
			amount: 500,
			transaction_type: "contribution",
			description: "Monthly TFSA contribution",
			transaction_date: "2024-12-01",
			linked_allocation_transaction_id: null,
			created_at: "2024-12-01T10:00:00Z",
		},
	],
	"acc-4": [
		{
			id: "txn-4",
			account_id: "acc-4",
			user_id: "sample-user",
			amount: 300,
			transaction_type: "payment",
			description: "Payment",
			transaction_date: "2024-12-10",
			linked_allocation_transaction_id: "tx-linked-debt",
			created_at: "2024-12-10T10:00:00Z",
		},
	],
};
