import { RecurringExpense } from "@/app/recurring/actions";

export const MOCK_RECURRING_EXPENSES: RecurringExpense[] = [
    {
        id: "mock-1",
        user_id: "mock-user",
        name: "Netflix",
        amount: 15.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 15).toISOString(), // 15th of this month
        category: "subscription",
        is_active: true,
        service_provider: "netflix",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-2",
        user_id: "mock-user",
        name: "Spotify",
        amount: 9.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 28).toISOString(), // 28th of this month
        category: "subscription",
        is_active: true,
        service_provider: "spotify",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-3",
        user_id: "mock-user",
        name: "Gym Membership",
        amount: 50.00,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString(), // 1st of this month
        category: "subscription",
        is_active: true,
        service_provider: null,
        plaid_stream_id: null,
        meta_data: { no_logo_lookup: true },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-4",
        user_id: "mock-user",
        name: "Rent",
        amount: 1200.00,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString(), // 1st of this month
        category: "bill",
        is_active: true,
        service_provider: "rent",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-5",
        user_id: "mock-user",
        name: "Electricity Bill",
        amount: 85.00,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 20).toISOString(), // 20th of this month
        category: "bill",
        is_active: true,
        service_provider: null,
        plaid_stream_id: null,
        meta_data: { no_logo_lookup: true },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-6",
        user_id: "mock-user",
        name: "Amazon Prime",
        amount: 139.00,
        currency: "USD",
        billing_period: "yearly",
        next_due_date: new Date(new Date().getFullYear() + 1, 5, 15).toISOString(), // Next year, June 15th
        category: "subscription",
        is_active: true,
        service_provider: "prime",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        status: "upcoming"
    },
    // Additional mock data for testing logo.dev API
    {
        id: "mock-7",
        user_id: "mock-user",
        name: "Adobe Creative Cloud",
        amount: 54.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 10).toISOString(),
        category: "subscription",
        is_active: true,
        service_provider: "adobe", // Using provider for logo lookup
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-8",
        user_id: "mock-user",
        name: "Dropbox Plus",
        amount: 11.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 5).toISOString(),
        category: "subscription",
        is_active: true,
        service_provider: "dropbox",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-9",
        user_id: "mock-user",
        name: "Slack",
        amount: 8.75,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 12).toISOString(),
        category: "subscription",
        is_active: true,
        service_provider: "slack",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-10",
        user_id: "mock-user",
        name: "GitHub Pro",
        amount: 4.00,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 8).toISOString(),
        category: "subscription",
        is_active: false, // Testing inactive subscription
        service_provider: "github",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-11",
        user_id: "mock-user",
        name: "Disney Plus",
        amount: 13.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 22).toISOString(),
        category: "subscription",
        is_active: true,
        service_provider: "disneyplus",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-12",
        user_id: "mock-user",
        name: "Internet Bill",
        amount: 79.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 18).toISOString(),
        category: "bill",
        is_active: true,
        service_provider: "comcast",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

