import { RecurringExpense } from "@/app/recurring/actions";

export const MOCK_RECURRING_EXPENSES: RecurringExpense[] = [
    {
        id: "mock-1",
        user_id: "mock-user",
        name: "Netflix",
        amount: 15.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 15).toISOString(), // 15th of this month
        category: "subscription",
        is_active: true,
        service_provider: "netflix",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-2",
        user_id: "mock-user",
        name: "Spotify",
        amount: 9.99,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 28).toISOString(), // 28th of this month
        category: "subscription",
        is_active: true,
        service_provider: "spotify",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-3",
        user_id: "mock-user",
        name: "Gym Membership",
        amount: 50.00,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString(), // 1st of this month
        category: "subscription",
        is_active: true,
        service_provider: "custom_sub",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-4",
        user_id: "mock-user",
        name: "Rent",
        amount: 1200.00,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString(), // 1st of this month
        category: "bill",
        is_active: true,
        service_provider: "rent",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-5",
        user_id: "mock-user",
        name: "Electricity Bill",
        amount: 85.00,
        currency: "USD",
        billing_period: "monthly",
        next_due_date: new Date(new Date().getFullYear(), new Date().getMonth(), 20).toISOString(), // 20th of this month
        category: "bill",
        is_active: true,
        service_provider: "custom_bill",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "mock-6",
        user_id: "mock-user",
        name: "Amazon Prime",
        amount: 139.00,
        currency: "USD",
        billing_period: "yearly",
        next_due_date: new Date(new Date().getFullYear() + 1, 5, 15).toISOString(), // Next year, June 15th
        category: "subscription",
        is_active: true,
        service_provider: "prime",
        plaid_stream_id: null,
        meta_data: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        status: "upcoming"
    }
];
